### ISSUE TITLE
docker image pushes regularly timing out on CI

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1052]
### Describe the bug

CI builds that need to create the CI runner docker images regularly spuriously fail due to timeouts, e.g. 
- https://buildkite.com/stellar/stellargraph-public/builds/2093
- https://buildkite.com/stellar/stellargraph-public/builds/2106
- https://buildkite.com/stellar/stellargraph-public/builds/2115
- https://buildkite.com/stellar/stellargraph-public/builds/2120

### To Reproduce

1. do a build that needs to rebuild the runner docker images, by editing the `setup.py` file or by setting the `REFRESH_BUILD` environment variable

### Observed behavior

```
$ docker-compose -f docker-compose.yml -f .buildkite/docker-compose.yml -p buildkite14f894d543f14225b82dd55876eead07 -f docker-compose.buildkite-2115-override.yml push runner-3_6
Pushing runner-3_6 (index.docker.io/stellargraph/stellargraph-ci-runner:stellargraph-public-runner-3_6-build-2115)...
The push refers to repository [docker.io/stellargraph/stellargraph-ci-runner]
f7a461be6ae1: Pushing [==================================================>]   1.98GB
6549c38ac551: Pushed
a4d8ea61eee6: Pushed
71fda9870934: Layer already exists
8ec6a04f59d6: Layer already exists
4d42b373e1b2: Layer already exists
352d42e186c2: Layer already exists
ba924bce9f5a: Layer already exists
271910c4c150: Layer already exists
6670e930ed33: Layer already exists
c7f27a4eb870: Layer already exists
e70dfb4c3a48: Layer already exists
1c76bd0dc325: Layer already exists
Traceback (most recent call last):
  File "site-packages/urllib3/response.py", line 362, in _error_catcher
  File "site-packages/urllib3/response.py", line 444, in read
  File "http/client.py", line 449, in read
  File "http/client.py", line 483, in readinto
  File "http/client.py", line 578, in _readinto_chunked
  File "http/client.py", line 546, in _get_chunk_left
  File "http/client.py", line 506, in _read_next_chunk_size
  File "socket.py", line 586, in readinto
socket.timeout: timed out
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 776, in push
  File "compose/project.py", line 654, in push
  File "compose/service.py", line 1235, in push
  File "compose/progress_stream.py", line 112, in get_digest_from_push
  File "compose/progress_stream.py", line 25, in stream_output
  File "compose/utils.py", line 61, in split_buffer
  File "compose/utils.py", line 37, in stream_as_text
  File "site-packages/docker/api/client.py", line 345, in _stream_helper
  File "site-packages/urllib3/response.py", line 461, in read
  File "contextlib.py", line 99, in __exit__
  File "site-packages/urllib3/response.py", line 367, in _error_catcher
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
[1949] Failed to execute script docker-compose
Exited with 255
```
### Expected behavior

The job shouldn't time out for ~any push
### Environment

Operating system: CI

Python version: N/A

Package versions: N/A

### Additional context

N/A

**Comment by huonw** [comment]
https://github.com/stellargraph/stellargraph/pull/1048#pullrequestreview-371671833 has some more discussion about the failure/problems here.
