### ISSUE TITLE
Saliency map GAT input shape error

### ISSUE THREAD

**Issue by anfoss** [stellargraph/stellargraph#1867]
### Describe the bug

I trained a GAT for binary node classification with the following structure

```
    __________________________________________________________________________________________________
    Layer (type)                    Output Shape         Param #     Connected to                     
    ==================================================================================================
    input_1 (InputLayer)            [(1, 20379, 51)]     0                                            
    __________________________________________________________________________________________________
    input_3 (InputLayer)            [(1, None, 2)]       0                                            
    __________________________________________________________________________________________________
    input_4 (InputLayer)            [(1, None)]          0                                            
    __________________________________________________________________________________________________
    dropout (Dropout)               (1, 20379, 51)       0           input_1[0][0]                    
    __________________________________________________________________________________________________
    squeezed_sparse_conversion (Squ (20379, 20379)       0           input_3[0][0]                    
                                                                     input_4[0][0]                    
    __________________________________________________________________________________________________
    graph_attention_sparse (GraphAt (1, 20379, 128)      6914        dropout[0][0]                    
                                                                     squeezed_sparse_conversion[0][0] 
    __________________________________________________________________________________________________
    dropout_1 (Dropout)             (1, 20379, 128)      0           graph_attention_sparse[0][0]     
    __________________________________________________________________________________________________
    graph_attention_sparse_1 (Graph (1, 20379, 1)        133         dropout_1[0][0]                  
                                                                     squeezed_sparse_conversion[0][0] 
    __________________________________________________________________________________________________
    input_2 (InputLayer)            [(1, None)]          0                                            
    __________________________________________________________________________________________________
    gather_indices (GatherIndices)  (1, None, 1)         0           graph_attention_sparse_1[0][0]   
                                                                     input_2[0][0]                    
    __________________________________________________________________________________________________
    lambda (Lambda)                 (1, None, 1)         0           gather_indices[0][0]             
    ==================================================================================================
    Total params: 7,047
    Trainable params: 7,043
    Non-trainable params: 4
```

I saved the model with model.save() and then used the following code to obtain node self-importance following https://stellargraph.readthedocs.io/en/stable/demos/interpretability/gat-node-link-importance.html?highlight=GAT%20saliency

```python
    G = StellarGraph(X, edges=conv2adj_list(adj_matrix))
    generator = FullBatchNodeGenerator(G, method="gat", sparse=False)
    train_gen = generator.flow(train_subjects.index, train_targets)
    model = tf.keras.models.load_model('GAT10_2layers', custom_objects={'mcc':mcc})
    create_file('out/gat_saliency_nodes.txt', ['node id', 'self-importance', 'pred', 'class'])
    int_grad_saliency = IntegratedGradientsGAT(model, train_gen, generator.node_list)
    saliency = GradientSaliencyGAT(model, train_gen)
```

but the IntegratedGradientsGAT fails with too many arguments to unpack expected 3.

print(model.input) returns 4 inputs.

```
[<KerasTensor: shape=(1, 20379, 51) dtype=float32 (created by layer 'input_1')>, <KerasTensor: shape=(1, None) dtype=int32 (created by layer 'input_2')>, <KerasTensor: shape=(1, None, 2) dtype=int64 (created by layer 'input_3')>, <KerasTensor: shape=(1, None) dtype=float32 (created by layer 'input_4')>]
```

I am using the same generator / inputs/labels for training and saliency, is there something obvious that I am missing?

**Comment by huonw** [comment]
Thanks for filing an issue! I think I'll need a little bit more info:

- What's the exact error message/stack trace?
- What's the code used to create the `GAT` model? 
- Could you try running the `IntegratedGradientsGAT` construction in the original code and see if it fails in the same way? (You can do this after compiling but without training, if training takes a long time.) That is, it'd be good to narrow down whether this is caused by saving/loading, or is unrelated to that.


---

FYI, I edited your issue text to fix a minor markdown mistake: a multi-line code blocks are much easier to read using three backticks rather than just one, for example:

~~~
```python
G = StellarGraph(X, edges=conv2adj_list(adj_matrix))
generator = FullBatchNodeGenerator(G, method="gat", sparse=False)
train_gen = generator.flow(train_subjects.index, train_targets)
model = tf.keras.models.load_model('GAT10_2layers', custom_objects={'mcc':mcc})
create_file('out/gat_saliency_nodes.txt', ['node id', 'self-importance', 'pred', 'class'])
int_grad_saliency = IntegratedGradientsGAT(model, train_gen, generator.node_list)
saliency = GradientSaliencyGAT(model, train_gen)
```
~~~

(It's easy to forget, so Github has a nice little guide with examples as a reminder: https://guides.github.com/features/mastering-markdown/#examples . It's linked in comment boxes as the little `M↓` logo in the bottom right corner.)

**Comment by anfoss** [comment]
Thanks for fixing the formatting, missed to preview it before posting.
Answering to your questions the full stack of the error is the following

```
Traceback (most recent call last):
  File "gat_saliencymaps.py", line 141, in <module>
    int_grad_saliency = IntegratedGradientsGAT(model, train_gen, generator.node_list)
  File "/Users/anfossat/opt/anaconda3/lib/python3.7/site-packages/stellargraph/interpretability/saliency_maps/integrated_gradients_gat.py", line 43, in __init__
    super().__init__(model, generator)
  File "/Users/anfossat/opt/anaconda3/lib/python3.7/site-packages/stellargraph/interpretability/saliency_maps/saliency_gat.py", line 59, in __init__
    features_t, output_indices_t, adj_t = model.input
ValueError: too many values to unpack (expected 3)

```

I created the GAT model with the following code 


```python



def conv2list(adj_m):
    """
    converts adjacency matrix to adj list
    """
    idx = np.triu_indices(n=adj_m.shape[0])
    v = adj_m[idx].reshape(-1, 1)
    col = idx[0].reshape(-1, 1)
    row = idx[1].reshape(-1, 1)
    final = np.concatenate((row, col, v), axis=1)
    d = pd.DataFrame(final)
    d.columns = ['source', 'target', 'weight']
    d = d[d['weight']>0]
    return d

def mcc(y_true, y_pred):
    y_pred_pos = K.round(K.clip(y_pred, 0, 1))
    y_pred_neg = 1 - y_pred_pos

    y_pos = K.round(K.clip(y_true, 0, 1))
    y_neg = 1 - y_pos

    tp = K.sum(y_pos * y_pred_pos)
    tn = K.sum(y_neg * y_pred_neg)

    fp = K.sum(y_neg * y_pred_pos)
    fn = K.sum(y_pos * y_pred_neg)

    numerator = (tp * tn - fp * fn)
    denominator = K.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))

    return numerator / (denominator + K.epsilon())

G = StellarGraph(X, edges=conv2list(A))
train_y, test_y = model_selection.train_test_split(
    y, test_size=0.2, stratify=y
)
val_y, test_y = model_selection.train_test_split(
    test_y, test_size=0.5, stratify=test_y
)

generator = FullBatchNodeGenerator(G, method="gat")
train_gen = generator.flow(train_y.index, train_y.values)

gat = GAT(
    layer_sizes=[16, 1],
    activations=["elu", "sigmoid"],
    attn_heads=8,
    generator=generator,
    in_dropout=0.3,
    attn_dropout=0.3,
    normalize=None,
    saliency_map_support=True
)

x_inp, x_out = gat.in_out_tensors()

model = Model(inputs=x_inp, outputs=x_out)

model.compile(
    optimizer=optimizers.Adam(lr=0.01),
    loss = BinaryCrossentropy(),
    metrics=[mcc, 'acc'],
)


log_dir = "logs/fit/tb"
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

checkpoint_name = './tmp_weights.hdf5'
checkpoint = ModelCheckpoint(checkpoint_name, monitor='val_loss', verbose = 1, save_best_only = True, mode ='min', patience=100)
stop = EarlyStopping(monitor='val_loss', min_delta=0.00001, patience=100, verbose=0, mode='auto')
callbacks_list = [checkpoint, stop, tensorboard_callback]

val_gen = generator.flow(val_subjects.index, val_targets)

history = model.fit(
    train_gen,
    shuffle=False,
    epochs=4000,
    verbose=2,
    validation_data=val_gen,
    callbacks = [callbacks_list]
)

model.load_weights("tmp_weights.hdf5")
model.save('GAT10_2layers')

```

The generator has the following shapes

```
G.info()
StellarGraph: Undirected multigraph
 Nodes: 20379, Edges: 20457

 Node types:
  default: [20379]
    Features: float64 vector, length 51
    Edge types: default-default->default

 Edge types:
    default-default->default: [20457]
        Weights: all 1 (default)
        Features: none

```

Running the IntegratedGradientSaliency without compiling fails with 


```
Traceback (most recent call last):
  File "trainGAT.py", line 150, in <module>
    int_grad_saliency = IntegratedGradientsGAT(model, generator, generator.node_list)
  File "/Users/anfossat/opt/anaconda3/lib/python3.7/site-packages/stellargraph/interpretability/saliency_maps/integrated_gradients_gat.py", line 43, in __init__
    super().__init__(model, generator)
  File "/Users/anfossat/opt/anaconda3/lib/python3.7/site-packages/stellargraph/interpretability/saliency_maps/saliency_gat.py", line 47, in __init__
    "The generator supplied has to be an object of FullBatchSequence."
TypeError: The generator supplied has to be an object of FullBatchSequence.

```

The generator passed is created by 

```
train_gen = generator.flow(train_subjects.index, train_targets)
```

**Comment by huonw** [comment]
Thanks for all the info! I think the problem is you're passing a sparse GAT model into `IntegratedGradientsGAT`, but it needs a dense one. In particular, https://github.com/stellargraph/stellargraph/issues/1839#issuecomment-756560275 is a little ambiguous but the key thing is having two `GAT` models (a sparse one for training, and a dense one for interpreting), which means `load_model` isn't quite right by itself. As a sketch, the code should look like:

```python
# sparse model for training
sparse_generator = FullBatchNodeGenerator(G, method="gat", sparse=True)
sparse_train_gen = sparse_generator.flow(...)

sparse_gat = GAT(
    ...,
    generator=sparse_generator,
    # don't need this support (but doesn't actually matter either way)
    saliency_map_support=False, 
)
# ...
sparse_model = Model(...) # things computed from dense_gat

# train (etc.) with sparse_model

# build a whole new model with sparse=False (i.e. dense adjacency matrix)
dense_generator = FullBatchNodeGenerator(G, method="gat", sparse=False)
dense_train_gen = dense_generator.flow(...)

dense_gat = GAT(
    ..., 
    # exactly the same parameters as sparse_gat, except for these two:
    generator=dense_generator,
    saliency_map_support=True,
)

dense_model = Model(...) # tensors computed from dense_gat

# transfer weights from sparse training model to dense interpretable model
# this could also be done with .load_weights(...) to load from a file
dense_model.set_weights(model.get_weights())

int_grad_saliency = IntegratedGradientsGAT(dense_model, dense_train_gen, dense_generator.node_list)
```

I've done a more complete sketch here: https://colab.research.google.com/drive/1KjO3T1oHTEcoIKsn4j75Fvgu-b9Lr0uo?usp=sharing .

The model architecture must be identical except for the `sparse` and `saliency_map_support` arguments, it may make sense to define a function like:

```python
def create_model(saliency):
    sparse = not saliency
    generator = FullBatchNodeGenerator(G, method="gat", sparse=sparse)
    gat = GAT(..., generator=generator, saliency_map_support=saliency)
    x_inp, x_out = gat.in_out_tensors()
    ...
    model = Model(...)

    return generator, gat, model

sparse_generator, sparse_gat, sparse_model = create_model(saliency=False)
dense_generator, dense_gat, dense_model = create_model(saliency=True)
``` 

---

The error message here could definitely be much improved. I think it could be done before the existing `FullBatchSequence` check in the following (this is theoretically covered by the `FullBatchSequence` check, but as you've observed, it's easy to mix and match a sparse model with a dense generator): https://github.com/stellargraph/stellargraph/blob/6e4ab0f5f76e452af50d0b807a59359906a2bee2/stellargraph/interpretability/saliency_maps/saliency_gat.py#L45-L49

by adding something like:

```python
if model.use_sparse:
    raise ValueError("model: expected a non-sparse GAT model, found a sparse one; use FullBatchNodeGenerator(..., sparse=False) to create the generator")
```

Feel free to submit a pull request adding this, and maybe even including a hint about the sparse -> dense weight transfer if you think that would be helpful. It might also be nice to rephrase the `FullBatchSequence` error message to be more helpful, like `generator: expected a FullBatchSequence produced by a FullBatchNodeGenerator(..., sparse=False), found {type(generator).__name__}`.

---

> Running the IntegratedGradientSaliency without compiling fails with

FWIW, I think there's a typo in that particular code since the error message is something very different. The second argument should be `train_gen`, not `generator`:

```python
int_grad_saliency = IntegratedGradientsGAT(model, train_gen, generator.node_list)
```

**Comment by dylan-plummer** [comment]
Hi, I'm joining this thread after running into the same issue. Unfortunately using a dense generator is not an option as my graph has millions of nodes. Is there any workaround for computing saliency maps for large graphs?
