### ISSUE TITLE
CI breaks on "conda" job

### ISSUE THREAD

**Issue by sgrigory** [stellargraph/stellargraph#1988]
### Describe the bug

CI job `conda` in GHA breaks on the current `develop` branch: step `s-weigand/setup-conda@v1` installs Python 3.9, which in step `Conda build StellarGraph` contradicts with requirements in `setup.py`: https://github.com/stellargraph/stellargraph/blob/f9cb68a9b7849cc7754deb8c3460ab10589ff376/setup.py#L91

### To Reproduce

Run with broken `conda` job: https://github.com/stellargraph/stellargraph/runs/3864294442

### Observed behavior

<details>

<summary>See error trace</summary>

```
1m 4s
Run conda build . --no-anaconda-upload
  conda build . --no-anaconda-upload
  shell: /usr/bin/bash -e {0}
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from internal_defaults
INFO:conda_build.metadata:Attempting to finalize metadata for stellargraph
Attempting to finalize metadata for stellargraph
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['stellargraph-1.2.1-py_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

>## Package Plan ##

  environment location: /usr/share/miniconda/conda-bld/stellargraph_1633990644068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main                
    _openmp_mutex:    4.5-1_gnu               
    ca-certificates:  2021.9.30-h06a4308_1    
    certifi:          2021.5.30-py39h06a4308_0
    ld_impl_linux-64: 2.35.1-h7274673_9       
    libffi:           3.3-he6710b0_2          
    libgcc-ng:        9.3.0-h5101ec6_17       
    libgomp:          9.3.0-h5101ec6_17       
    libstdcxx-ng:     9.3.0-hd4cf53a_17       
    ncurses:          6.2-he6710b0_1          
    openssl:          1.1.1l-h7f8727e_0       
    pip:              21.2.4-py39h06a4308_0   
    python:           3.9.7-h12debd9_1        
    readline:         8.1-h27cfd23_0          
    setuptools:       58.0.4-py39h06a4308_0   
    sqlite:           3.36.0-hc218d9a_0       
    tk:               8.6.11-h1ccaba5_0       
    tzdata:           2021a-h5d7bf9c_0        
    wheel:            0.37.0-pyhd3eb1b0_1     
    xz:               5.2.5-h7b6447c_0        
    zlib:             1.2.11-h7b6447c_3       

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    Running command python setup.py egg_info
    /usr/share/miniconda/conda-bld/stellargraph_1633990644068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/setuptools/dist.py:487: UserWarning: Normalizing '1.3.0b' to '1.3.0b0'
      warnings.warn(tmpl.format(**locals()))
    running egg_info
    creating /tmp/pip-pip-egg-info-bvc9t0is/stellargraph.egg-info
    writing /tmp/pip-pip-egg-info-bvc9t0is/stellargraph.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-bvc9t0is/stellargraph.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-bvc9t0is/stellargraph.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-bvc9t0is/stellargraph.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-bvc9t0is/stellargraph.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-bvc9t0is/stellargraph.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'AUTHORS'
    writing manifest file '/tmp/pip-pip-egg-info-bvc9t0is/stellargraph.egg-info/SOURCES.txt'
ERROR: Package 'stellargraph' requires a different Python: 3.9.7 not in '<3.9.0,>=3.6.0'
Traceback (most recent call last):
Copying /home/runner/work/stellargraph/stellargraph to /usr/share/miniconda/conda-bld/stellargraph_1633990644068/work/
  File "/usr/share/miniconda/bin/conda-build", line 11, in <module>
source tree in: /usr/share/miniconda/conda-bld/stellargraph_1633990644068/work
    sys.exit(main())
export PREFIX=/usr/share/miniconda/conda-bld/stellargraph_1633990644068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
  File "/usr/share/miniconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 481, in main
export BUILD_PREFIX=/usr/share/miniconda/conda-bld/stellargraph_1633990644068/_build_env
    execute(sys.argv[1:])
export SRC_DIR=/usr/share/miniconda/conda-bld/stellargraph_1633990644068/work
  File "/usr/share/miniconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 470, in execute
Using pip 21.2.4 from $PREFIX/lib/python3.9/site-packages/pip (python 3.9)
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
Non-user install because user site-packages disabled
  File "/usr/share/miniconda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
Ignoring indexes: https://pypi.org/simple
    return build_tree(
Created temporary directory: /tmp/pip-ephem-wheel-cache-9yxazmt0
  File "/usr/share/miniconda/lib/python3.9/site-packages/conda_build/build.py", line 3085, in build_tree
Created temporary directory: /tmp/pip-req-tracker-v6p5w16c
    packages_from_this = build(metadata, stats,
Initialized build tracking at /tmp/pip-req-tracker-v6p5w16c
  File "/usr/share/miniconda/lib/python3.9/site-packages/conda_build/build.py", line 2208, in build
Created build tracker: /tmp/pip-req-tracker-v6p5w16c
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
Entered build tracker: /tmp/pip-req-tracker-v6p5w16c
  File "/usr/share/miniconda/lib/python3.9/site-packages/conda_build/utils.py", line 412, in check_call_env
Created temporary directory: /tmp/pip-install-6voyttlx
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
Processing $SRC_DIR
  File "/usr/share/miniconda/lib/python3.9/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
  Created temporary directory: /tmp/pip-req-build-r9_m20ul
    raise subprocess.CalledProcessError(proc.returncode, _args)
  Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-v6p5w16c'
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/usr/share/miniconda/conda-bld/stellargraph_1633990644068/work/conda_build.sh']' returned non-zero exit status 1.
    Running setup.py (path:/tmp/pip-req-build-r9_m20ul/setup.py) egg_info for package from file://$SRC_DIR
    Created temporary directory: /tmp/pip-pip-egg-info-bvc9t0is
  Source in /tmp/pip-req-build-r9_m20ul has version 1.3.0b0, which satisfies requirement stellargraph==1.3.0b0 from file://$SRC_DIR
  Removed stellargraph==1.3.0b0 from file://$SRC_DIR from build tracker '/tmp/pip-req-tracker-v6p5w16c'
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "$PREFIX/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "$PREFIX/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 376, in resolve
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=RequiresPythonRequirement('<3.9.0,>=3.6.0'), parent=LinkCandidate('file://$SRC_DIR'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    raise error from e
pip._internal.exceptions.UnsupportedPythonVersion: Package 'stellargraph' requires a different Python: 3.9.7 not in '<3.9.0,>=3.6.0'
Removed build tracker: '/tmp/pip-req-tracker-v6p5w16c'
Error: Process completed with exit code 1.
0s
0s
0s

```

</details>

### Expected behavior

The job finishes successfully

### Environment

Operating system: Ubuntu 20.04.3

Python version: 3.9.7

### Proposed solution

One could pin Python version in the [`s-weigand/setup-conda@v1`  step](https://github.com/stellargraph/stellargraph/blob/f9cb68a9b7849cc7754deb8c3460ab10589ff376/.github/workflows/ci.yml#L337):

```
conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
         with:
           python-version: 3.8
      ...
```

**Comment by huonw** [comment]
Good catch, thank you!
