### ISSUE TITLE
Loading a saved HinSAGE link prediction model fails

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#201]
### Description
@adocherty this might happen with the yelp example as well! (once the `test()` function is implemented)

In branch `issue#186`:
When loading a HinSAGE+link regression model, saved by .train() in `/demos/link-prediction_hinsage/movielens-recommender.py`, with
```
model = keras.models.load_model(
            model_file, custom_objects={"MeanHinAggregator": MeanHinAggregator}
        )
```
the following error is thrown:
```
Traceback (most recent call last):
  File "/Users/tys017/Projects/Graph_Analytics/code/stellar-ml/demos/link-prediction_hinsage/movielens-recommender.py", line 376, in <module>
    model.test(args.checkpoint)
  File "/Users/tys017/Projects/Graph_Analytics/code/stellar-ml/demos/link-prediction_hinsage/movielens-recommender.py", line 256, in test
    model_file, custom_objects={"MeanHinAggregator": MeanHinAggregator}
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/models.py", line 270, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/models.py", line 347, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2535, in from_config
    process_node(layer, node_data)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2492, in process_node
    layer(input_tensors[0], **kwargs)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 638, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/layers/core.py", line 403, in compute_output_shape
    input_shape[1:], self.target_shape)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/layers/core.py", line 388, in _fix_unknown_dimension
    raise ValueError(msg)
ValueError: total size of new array must be unchanged
```

### Done Checklist (Development)
- [ ] Bug fixed
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented

**Comment by adocherty** [comment]
Added bug to Keras team issues:
https://github.com/keras-team/keras/issues/11159

**Comment by adocherty** [comment]
This is now a PR on Keras:
https://github.com/keras-team/keras/pull/11588

**Comment by adocherty** [comment]
This PR has now been merged into keras/master.

**Comment by youph** [comment]
@adocherty with the Keras bug fixed, loading a HinSAGE link prediction model still fails, with a different error message:
```
model = keras.models.load_model(
            model_file, custom_objects={"MeanHinAggregator": MeanHinAggregator}
        )
```
throws an error
```
Traceback (most recent call last):
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1576, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 8 and 1. Shapes are [?,8] and [?,1]. for 'mean_hin_aggregator_4/concat' (op: 'ConcatV2') with input shapes: [?,8,16], [?,1,16], [] and with computed input tensors: input[2] = <2>.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-421e31012cc3>", line 2, in <module>
    model_file, custom_objects={"MeanHinAggregator": MeanHinAggregator}
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/tys017/Projects/Graph_Analytics/code/stellar-ml/stellargraph/layer/hinsage.py", line 159, in call
    [from_self, from_neigh], axis=2
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1956, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1114, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1030, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1731, in __init__
    control_input_ops)
  File "/Users/tys017/anaconda3/envs/stellars_py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 8 and 1. Shapes are [?,8] and [?,1]. for 'mean_hin_aggregator_4/concat' (op: 'ConcatV2') with input shapes: [?,8,16], [?,1,16], [] and with computed input tensors: input[2] = <2>.
```

Any ideas?

**Comment by youph** [comment]
@adocherty loading a saved HinSAGE model for link prediction still fails - see above. To reproduce, checkout branch `issue#186` and run `demos/link-prediction/hinsage/movielens-recommender.py`. This should save the trained model into a file named something like `hinsage_link_pred_n8_4_l32_32_d0.0_r0.005.h5`. Re-run the demo script with the checkpoint option:
```
python movielens-recommender.py -c hinsage_link_pred_n8_4_l32_32_d0.0_r0.005.h5
```
I can't figure out what's wrong (looks like another keras bug?), asking for ideas.

**Comment by tianyugrab** [comment]
Hi @youph and @adocherty ,

I encountered the same error of "Dimension 1 in both shapes must be equal".
May I know if there is a fix now?

**Comment by illcat** [comment]
May I know if there is a fix now?

**Comment by enjieli** [comment]
what's the best way to save and load HinSAGE trained model? having a similar issue in loading the model after saving. But not sure I saved it right, `model.save('model/traits_only.h5')`
