### ISSUE TITLE
hinSAGE error using multiple node types: else {k: dim for k, _ in ([self.subtree_schema] + self.neigh_trees)[layer]} indexerror: list index out of range

### ISSUE THREAD

**Issue by Boraly** [stellargraph/stellargraph#2089]
### Describe the bug

I have follwing graph:
```
 StellarDiGraph: Directed multigraph
 Nodes: 1911, Edges: 2483

 Node types:
  Segment: [670]
    Features: float32 vector, length 1861
    Edge types: Segment-contains->Section, Segment-contains->Number, Segment-contains->Sentence
  Section: [382]
    Features: float32 vector, length 1861
    Edge types: Section-contains->Number, Section-contains->Sentence
  Book: [330]
    Features: float32 vector, length 1861
    Edge types: Book-contains->Section, Book-contains->Segment
  Example: [322]
    Features: float32 vector, length 1861
    Edge types: none
  Number: [108]
    Features: float32 vector, length 1861
    Edge types: Number-contains->Number
  Paper: [50]
    Features: float32 vector, length 2562
    Edge types: Paper-refers to->Section, Paper-refers to->Number, Paper-refers to->Segment, Paper-refers to->Example, Paper-refers to->Sentence
  Sentence: [49]
    Features: float32 vector, length 1861
    Edge types: Sentence-contains->Number

 Edge types:
    Book-contains->Segment: [670]
        Weights: all 1 (default)
        Features: none
    Paper-refers to->Segment: [416]
        Weights: all 1 (default)
        Features: none
    Segment-contains->Section: [381]
        Weights: all 1 (default)
        Features: none
    Paper-refers to->Section: [353]
        Weights: all 1 (default)
        Features: none
    Paper-refers to->Example: [328]
        Weights: all 1 (default)
        Features: none
    Paper-refers to->Number: [139]
        Weights: all 1 (default)
        Features: none
    Section-contains->Number: [69]
        Weights: all 1 (default)
        Features: none
    Paper-refers to->Sentence: [38]
        Weights: all 1 (default)
        Features: none
    Section-contains->Sentence: [36]
        Weights: all 1 (default)
        Features: none
    Segment-contains->Number: [22]
        Weights: all 1 (default)
        Features: none
    Sentence-contains->Number: [13]
        Weights: all 1 (default)
        Features: none
    Segment-contains->Sentence: [13]
        Weights: all 1 (default)
        Features: none
    Number-contains->Number: [4]
        Weights: all 1 (default)
        Features: none
    Book-contains->Section: [1]
        Weights: all 1 (default)
        Features: none
```

And I want to use the hinSAGE algo to train an embedding for the paper-type nodes. The paper-type nodes have a vector representation as the node feature. All other nodes have the identity as a feature. I try to get the embedding with the following code:

```
import time
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.manifold import TSNE
from sklearn.linear_model import LogisticRegression
import loadData
import preprocessing
import createNetwork

import stellargraph as sg
from stellargraph.mapper import CorruptedGenerator, HinSAGENodeGenerator
from stellargraph.layer import DeepGraphInfomax, HinSAGE, Dense
import stellargraph as StellarGraph

import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import Model, optimizers, losses, metrics


# Parameters
batch_size = 200
dropout = 0.4
verbose = 1
visualize = False
def createEmbeddings(G, papers):
    print("DeepGraphInfomax embedding Starting")

    t0 = time.time()

    verbose = 1


    '''
    HinSAGENodeGenerator(G, batch_size, num_samples, head_node_type=None, schema=None, seed=None, name=None)
    G = graph (stellargraph object)
    batch_size = size of batch to return
    num_samples = the number of samples per layer (hop) to take
    head_node_type = the node type that will be given to the generator using the flow method. 
                    The model will expect this type.
                    If not given, it defaults to a single node type.
                    Note: HinSAGE does aggregation on multiple node types 
                    but then predicts on one type.
    '''

    def create_embeddings(
            node_type, num_samples, hinsage_layer_sizes,
            epochs, patience, batch_size, dropout, activations):
        # Check if num_samples and layer_size are compatible

        assert len(hinsage_layer_sizes) == len(num_samples)

        generator = HinSAGENodeGenerator(
            G,
            batch_size=batch_size,
            num_samples=num_samples,
            head_node_type=node_type
        )

        # HinSAGE layers
        hinsage = HinSAGE(
            layer_sizes=hinsage_layer_sizes,
            activations=activations,
            generator=generator,
            bias=True,
            dropout=dropout
        )

        def run_deep_graph_infomax(base_model, generator, epochs, node_type):
            corrupted_generator = CorruptedGenerator(generator)
            gen = corrupted_generator.flow(G.nodes(node_type=node_type))
            infomax = DeepGraphInfomax(base_model, corrupted_generator)

            x_in, x_out = infomax.in_out_tensors()

            print("Starting Training")
            ttrain = time.time()
            # Train
            model = Model(inputs=x_in, outputs=x_out)
            model.compile(loss=tf.nn.sigmoid_cross_entropy_with_logits, optimizer=Adam(lr=1e-3))
            es = EarlyStopping(monitor="loss", min_delta=0, patience=patience)

            history = model.fit(gen, epochs=epochs, verbose=verbose, callbacks=[es])
            # sg.utils.plot_history(history)

            ttrain1 = time.time()
            print(f"Training complete in {(ttrain1 - ttrain):.2f} s ({(ttrain1 - ttrain) / 60:.2f} min)")

            x_emb_in, x_emb_out = base_model.in_out_tensors()
            # for full batch models, squeeze out the batch dim (which is 1)
            if generator.num_batch_dims() == 2:
                x_emb_out = tf.squeeze(x_emb_out, axis=0)

            return x_emb_in, x_emb_out

        # Run Deep Graph Infomax
        x_emb_in, x_emb_out = run_deep_graph_infomax(
            hinsage, generator, epochs=epochs, node_type=node_type)

        emb_model = Model(inputs=x_emb_in, outputs=x_emb_out)
        all_embeddings = emb_model.predict(
            generator.flow(G.nodes(node_type=node_type))
        )

        # TSNE visualization of embeddings
        ttsne = time.time()
        print("Creating TSNE")
        embeddings_2d = pd.DataFrame(TSNE(n_components=2).fit_transform(all_embeddings),
                                     index=G.nodes(node_type=node_type))

        # draw the points (colors based on ExtendedCaseGraphID)
        node_ids = G.nodes(node_type=node_type).tolist()
        ext_targets = [jud._register_char for jud in papers]

        label_map = {l: i * 10 for i, l in enumerate(np.unique(ext_targets), start=10) if pd.notna(l)}
        node_colours = [label_map[target] if pd.notna(target) else 0 for target in ext_targets]

        ttsne1 = time.time()
        print(f"TSNE completed in {(ttsne1 - ttsne):.2f} s ({(ttsne1 - ttsne) / 60:.2f} min)")

        alpha = 0.7
        fig, ax = plt.subplots(figsize=(15, 15))
        ax.scatter(
            embeddings_2d[0],
            embeddings_2d[1],
            c=node_colours,
            cmap="jet",
            alpha=alpha,
        )
        ax.set(aspect="equal")
        plt.title(f'TSNE visualization of HinSAGE "{node_type}" embeddings with Deep Graph Infomax')
        plt.savefig(f"./embeddings/HinSAGE_DGI_embeddings_{node_type}.pdf")

        return all_embeddings, embeddings_2d, emb_model

    paper_embeddings, paper_2d, emb_model = create_embeddings(
        node_type="Paper",
        epochs=75,
        patience=25,
        batch_size=250,
        dropout=0.4,
        num_samples=[8, 4],
        hinsage_layer_sizes=[32, 32],
        activations=['relu', 'relu']
    )

    t1 = time.time()
    print(f"HinSAGE DGI completed in {(t1 - t0):.2f} s ({(t1 - t0) / 60:.2f} min)")

    return paper_embeddings, paper_2d, emb_model


if __name__ == '__main__':
    df = loadData.loadDataFrameFromJson('data/test50.json')
    listOfPapers = preprocessing.dfToPaperObjects(df)
    graph = createNetwork.create_law_network(listOfPapers)
    G = createNetwork.networkXtoStellargraph(graph, listOfPapers)

    paper_embeddings, paper_2d, emb_model = createEmbeddings(G,listOfPapers)
```

### Observed behavior

I get following error message:
`Traceback (most recent call last):
  File "C:\Users\Username\PycharmProjects\project\hingeSAGEEmbedding.py", line 164, in <module>
    judgment_embeddings, judgment_2d, emb_model = createEmbeddings(G,listOfJudgements)
  File "C:\Users\Username\PycharmProjects\project\hingeSAGEEmbedding.py", line 141, in createEmbeddings
    judgment_embeddings, judgment_2d, emb_model = create_embeddings(
  File "C:\Users\Username\PycharmProjects\project\hingeSAGEEmbedding.py", line 66, in create_embeddings
    hinsage = HinSAGE(
  File "C:\Users\Username\anaconda3\envs\project\lib\site-packages\stellargraph\layer\hinsage.py", line 401, in __init__
    self.dims = [
  File "C:\Users\Username\anaconda3\envs\project\lib\site-packages\stellargraph\layer\hinsage.py", line 404, in <listcomp>
    else {k: dim for k, _ in ([self.subtree_schema] + self.neigh_trees)[layer]}
IndexError: list index out of range`

I tried to debug the code with this example:
```
    subtree_schema = [('Paper', [1, 2, 3, 4, 5]), ('Section', [6, 7]), ('Number', []), ('Segment', [8, 9, 10]),
                      ('Example', []), ('Sentence', [11]), ('Number', []), ('Sentence', []), ('Section', []),
                      ('Number', []), ('Sentence', []), ('Number', [])]
    neigh_trees = [[('Paper', [1, 2, 3, 4, 5]), ('Section', [6, 7]), ('Segment', [8, 9, 10]), ('Sentence', [11])]]
    input_dims = {'Section': 1340, 'Book': 1340, 'Paper': 2562, 'Number': 1340, 'Segment': 1340,
                  'Example': 1340, 'Sentence': 1340}
    layer_sizes = [32, 32]
    for layer, dim in enumerate([input_dims] + layer_sizes):
        if isinstance(dim, dict):
            print(dim)
        else:
            for k, _ in ([subtree_schema] + neigh_trees)[layer]:
                print(k, dim)
```
Because of the layer_size [32,32] i enumerate trough 3 layers (0,1,2). But ([subtree_schema] + neigh_trees) doesn't have the layer 2. I dont know If I made a mistake with my inputs or if its a bug in the code.

### Environment

Operating system: Windows 10

# Name                    Version                   Build  Channel      
_tflow_select             2.3.0                       mkl  
abseil-cpp                20211102.0           hd77b12b_0  
absl-py                   1.3.0            py38haa95532_0  
aiohttp                   3.8.3            py38h2bbff1b_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
astunparse                1.6.3                      py_0  
async-timeout             4.0.2            py38haa95532_0
attrs                     22.1.0           py38haa95532_0
blas                      1.0                         mkl
blinker                   1.4              py38haa95532_0
brotlipy                  0.7.0           py38h2bbff1b_1003
c-ares                    1.19.0               h2bbff1b_0
ca-certificates           2023.01.10           haa95532_0
cachetools                4.2.2              pyhd3eb1b0_0
certifi                   2022.12.7        py38haa95532_0
cffi                      1.15.1           py38h2bbff1b_3
chardet                   5.1.0                    pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.0.4            py38haa95532_0
colorama                  0.4.6            py38haa95532_0
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.1           py38h21b164f_0
cycler                    0.11.0                   pypi_0    pypi
flatbuffers               2.0.0                h6c2663c_0
fonttools                 4.39.3                   pypi_0    pypi
frozenlist                1.3.3            py38h2bbff1b_0
gast                      0.4.0              pyhd3eb1b0_0
gensim                    4.3.1                    pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3
google-auth               2.6.0              pyhd3eb1b0_0
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0
google-pasta              0.2.0              pyhd3eb1b0_0
grpc-cpp                  1.48.2               hf108199_0
grpcio                    1.48.2           py38hf108199_0
h5py                      3.7.0            py38h3de5c98_0
hdf5                      1.10.6               h1756f20_1
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.4              py38haa95532_0
importlib-metadata        6.0.0            py38haa95532_0
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
joblib                    1.1.1            py38haa95532_0
jpeg                      9e                   h2bbff1b_1
keras                     2.10.0           py38haa95532_0
keras-preprocessing       1.1.2              pyhd3eb1b0_0
kiwisolver                1.4.4                    pypi_0    pypi
legal-reference-extraction 0.2.0                    pypi_0    pypi
libclang                  16.0.0                   pypi_0    pypi
libcurl                   7.88.1               h86230a5_0
libffi                    3.4.2                hd77b12b_6
libpng                    1.6.39               h8cc25b3_0
libprotobuf               3.20.3               h23ce68f_0
libssh2                   1.10.0               hcd4344a_0
markdown                  3.4.1            py38haa95532_0
markupsafe                2.1.1            py38h2bbff1b_0
matplotlib                3.7.1                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.1            py38h277e83a_0
mkl_random                1.2.2            py38hf11a4ad_0
multidict                 6.0.2            py38h2bbff1b_0
networkx                  3.1                      pypi_0    pypi
nltk                      3.4.5                    pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
numpy-base                1.23.5           py38h4da318b_0
oauthlib                  3.2.2            py38haa95532_0
openssl                   1.1.1t               h2bbff1b_0
opt_einsum                3.3.0              pyhd3eb1b0_1
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.0                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1           py38haa95532_0
pooch                     1.4.0              pyhd3eb1b0_0
protobuf                  3.19.6                   pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pycparser                 2.21               pyhd3eb1b0_0
pyjwt                     2.4.0            py38haa95532_0
pyopenssl                 23.0.0           py38haa95532_0
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0
python                    3.8.16               h6244533_3
python-dateutil           2.8.2                    pypi_0    pypi
python-flatbuffers        2.0                pyhd3eb1b0_0
pytz                      2023.3                   pypi_0    pypi
re2                       2022.04.01           hd77b12b_0
regex                     2022.7.9         py38h2bbff1b_0
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.0                      py_0
rsa                       4.7.2              pyhd3eb1b0_1
scikit-learn              1.2.2            py38hd77b12b_0
scipy                     1.10.1           py38h321e85e_0
seaborn                   0.12.2                   pypi_0    pypi
setuptools                67.6.1                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
smart-open                6.3.0                    pypi_0    pypi
snappy                    1.1.9                h6c2663c_0
sqlite                    3.41.2               h2bbff1b_0
stellargraph              1.2.1                    pypi_0    pypi
tensorboard               2.10.0           py38haa95532_0
tensorboard-data-server   0.6.1            py38haa95532_0
tensorboard-plugin-wit    1.8.1            py38haa95532_0
tensorflow                2.10.0          mkl_py38ha5c4042_0
tensorflow-base           2.10.0          mkl_py38h6a7f48e_0
tensorflow-estimator      2.10.0           py38haa95532_0
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 2.1.0            py38haa95532_0
threadpoolctl             2.2.0              pyh0d69192_0
tqdm                      4.65.0           py38hd4e2768_0
typing_extensions         4.5.0            py38haa95532_0
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.15          py38haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
werkzeug                  2.2.3            py38haa95532_0
wheel                     0.38.4           py38haa95532_0
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2              py38haa95532_2
wrapt                     1.14.1           py38h2bbff1b_0
yarl                      1.8.1            py38h2bbff1b_0
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0

Hope someone can help!

**Comment by Boraly** [comment]
I saw that I had only on head_node_type but two layers. Changed the layers to a one size list. That fixed it.
