### ISSUE TITLE
Can't run "Node representation learning with Deep Graph Infomax" demo

### ISSUE THREAD

**Issue by mlanvin** [stellargraph/stellargraph#2092]
I don't manage to make the "Node representation learning with Deep Graph Infomax" demo work. I would especially like to **extract the embeddings**.

I downloaded the notebook locally from the demo page : https://stellargraph.readthedocs.io/en/stable/demos/embeddings/deep-graph-infomax-embeddings.html

I am working under Fedora with **python3.8** and the following package versions :

- **numpy**                        1.23.5
- **pandas**                       2.0.1
- **notebook**                     6.5.4
- **stellargraph**                 1.2.1
- **tensorflow**                   2.12.0

The error occurs when the `predict` method is called in the following cell:

```python
train_subjects, test_subjects = model_selection.train_test_split(
    node_subjects, train_size=0.1, test_size=None, stratify=node_subjects
)

test_gen = fullbatch_generator.flow(test_subjects.index)
train_gen = fullbatch_generator.flow(train_subjects.index)

test_embeddings = emb_model.predict(test_gen)
train_embeddings = emb_model.predict(train_gen)

lr = LogisticRegression(multi_class="auto", solver="lbfgs")
lr.fit(train_embeddings, train_subjects)

y_pred = lr.predict(test_embeddings)
gcn_acc = (y_pred == test_subjects).mean()
print(f"Test classification accuracy: {gcn_acc}")
``` 

The error stack is the following one: 

```java
ValueError                                Traceback (most recent call last)
Cell In[10], line 8
      5 test_gen = fullbatch_generator.flow(test_subjects.index)
      6 train_gen = fullbatch_generator.flow(train_subjects.index)
----> 8 test_embeddings = emb_model.predict(test_gen)
      9 train_embeddings = emb_model.predict(train_gen)
     11 lr = LogisticRegression(multi_class="auto", solver="lbfgs")

File ~/.../lib/python3.8/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /tmp/__autograph_generated_file8t_xiojj.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__predict_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

ValueError: in user code:

    File ".../lib/python3.8/site-packages/keras/engine/training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File ".../lib/python3.8/site-packages/keras/engine/training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File ".../lib/python3.8/site-packages/keras/engine/training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File ".../lib/python3.8/site-packages/keras/engine/training.py", line 2111, in predict_step
        return self(x, training=False)
    File ".../lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File ".../lib/python3.8/site-packages/keras/engine/input_spec.py", line 219, in assert_input_compatibility
        raise ValueError(

    ValueError: Layer "model_2" expects 3 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, None) dtype=float32>]
``` 
Could you please help me fix this issue?

**Comment by mlanvin** [comment]
Using the 2.10 version of tensorflow fixed the issue. However, this means that the module does not work with tensorflow 2.12, which is more recent.
